In [6]:
import numpy as np
import pandas as pd

In [7]:
movies = pd.read_csv('movies.csv')
credits = pd.read_csv('credits.csv')

In [8]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [9]:
movies= movies.merge(credits,on='title')

In [10]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [11]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [12]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
movies.dropna(inplace=True)

In [20]:
movies.duplicated().sum()

0

In [21]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [22]:
import ast
ast.literal_eval('[{"id": 11, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]')

[{'id': 11, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 28, 'name': 'Action'}]

In [23]:
movies.iloc[1].genres

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [20]:
movies['genres'] = movies['genres'].apply(convert)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies['keywords'] = movies['keywords'].apply(convert)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [28]:
movies['cast'] = movies['cast'].apply(convert3)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [31]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [34]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [36]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [37]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [38]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [39]:
new_df = movies[['movie_id','title','tags']]

In [40]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [41]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-41-ad44e9ca1347>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [42]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [43]:
new_df['tags'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. [ { " i d " :  1 2 ,  " n a m e " :  " A d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " F a n t a s y " } ,  { " i d " :  2 8 ,  " n a m e " :  " A c t i o n " } ] ocean drugabuse exoticisland eastindiatradingcompany loveofone\'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger JohnnyDepp OrlandoBloom KeiraKnightley GoreVerbinski'

In [44]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<ipython-input-44-8b60b591a07f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [45]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [46]:
import nltk

In [47]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [48]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [49]:
new_df['tags'][1]

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. [ { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ] ocean drugabuse exoticisland eastindiatradingcompany loveofone\'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski'

In [50]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " a c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " a d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " f a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " s c i e n c e  f i c t i o n " } ] cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [52]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [54]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
vectors[2]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [56]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusement',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attempttoescape',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'bid',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'burned',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'childprodigy',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cigarettesmoking',
 'cillianmurphy',
 'cindy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 ...]

In [57]:
ps.stem('danced')

'danc'

In [58]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [59]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-59-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

In [61]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.        , ..., 0.        , 0.02752409,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02865341, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.02865341, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02865341, 0.02865341, ..., 1.        , 0.048795  ,
        0.05006262],
       [0.02752409, 0.        , 0.        , ..., 0.048795  , 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.05006262, 0.05129892,
        1.        ]])

In [62]:
cosine_similarity(vectors).shape

(4806, 4806)

In [63]:
similarity = cosine_similarity(vectors)

In [64]:
sorted(list(enumerate(similarity[2])),reverse=True,key=lambda x:x[1])[1:6]

[(1346, 0.32258958354055234),
 (11, 0.31388241028717223),
 (29, 0.2948309470803936),
 (1723, 0.25560859370538297),
 (3166, 0.2373222262672836)]

In [65]:
sorted(similarity[0],reverse=True)

[1.0000000000000004,
 0.21320071635561044,
 0.20769510081357428,
 0.2059714602177749,
 0.20533080093573816,
 0.20100756305184245,
 0.20032733246124987,
 0.19500597976723483,
 0.18582615562066462,
 0.17654696590094993,
 0.17407765595569785,
 0.16888013236829963,
 0.16000261230887305,
 0.15974461276617435,
 0.15891043154093204,
 0.1574591643244434,
 0.15569978883230462,
 0.1556997888323046,
 0.1556997888323046,
 0.1519474352795173,
 0.1519474352795173,
 0.149270358506633,
 0.1488687935206897,
 0.14519080172812557,
 0.14519080172812557,
 0.14506471329641488,
 0.14213381090374033,
 0.14213381090374033,
 0.1411956236812263,
 0.14083575804390608,
 0.13957263155977065,
 0.13957263155977065,
 0.1392621247645583,
 0.13834289277321493,
 0.13593181195675924,
 0.13400504203456162,
 0.13373015960759796,
 0.13373015960759796,
 0.1315903389919538,
 0.1305582419667734,
 0.12833175058483634,
 0.12562972690740154,
 0.1250610798961445,
 0.1250610798961445,
 0.11980845957463077,
 0.11769797726729994,
 0.11677484162422844,
 0.11631052629980888,
 0.1160517706371319,
 0.1160517706371319,
 0.1160517706371319,
 0.1160517706371319,
 0.11528574397767913,
 0.1144727614064285,
 0.11396057645963797,
 0.11295649894498103,
 0.11149893466761211,
 0.11149893466761211,
 0.11149893466761211,
 0.11009637651263607,
 0.10744306187005072,
 0.10497277621629561,
 0.10444659357341872,
 0.10444659357341872,
 0.10444659357341872,
 0.10379985922153641,
 0.1037998592215364,
 0.1037998592215364,
 0.10156734322380513,
 0.09947294626039876,
 0.0984731927834662,
 0.0969762275752854,
 0.0969762275752854,
 0.09656090991705353,
 0.09564561997176209,
 0.09564561997176209,
 0.09534625892455922,
 0.09389050536260406,
 0.09379580992210837,
 0.0930484210398471,
 0.09231861823449955,
 0.09231861823449955,
 0.09143006417649888,
 0.09143006417649888,
 0.09090909090909093,
 0.08989331499509894,
 0.08989331499509894,
 0.08956221510397981,
 0.08956221510397981,
 0.08827348295047496,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.0863667034175061,
 0.08585457105482137,
 0.08471737420873576,
 0.08471737420873576,
 0.08444006618414981,
 0.08444006618414981,
 0.08444006618414981,
 0.08444006618414981,
 0.08444006618414981,
 0.08444006618414981,
 0.08444006618414981,
 0.08362420100070908,
 0.08362420100070908,
 0.08263686767584087,
 0.08257228238447706,
 0.08257228238447706,
 0.08206099398622184,
 0.08206099398622184,
 0.08206099398622184,
 0.08155908717405554,
 0.08058229640253804,
 0.08058229640253804,
 0.08040302522073696,
 0.07987230638308718,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.07784989441615231,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.07617550741785385,
 0.07597371763975865,
 0.07597371763975865,
 0.07597371763975865,
 0.07597371763975865,
 0.07597371763975865,
 0.07597371763975865,
 0.07597371763975865,
 0.07597371763975865,
 0.07460470969529907,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07385489458759964,
 0.07299318686018119,
 0.07259540086406278,
 0.07259540086406278,
 0.07259540086406278,
 0.07259540086406278,
 0.07259540086406278,
 0.07259540086406278,
 0.07173421497882157,
 0.07173421497882157,
 0.07106690545187017,
 0.07106690545187017,
 0.07106690545187017,
 0.07106690545187017,
 0.07106690545187017,
 0.07041787902195304,
 0.06963106238227915,
 0.06963106238227915,
 0.06963106238227915,
 0.06963106238227915,
 0.06963106238227915,
 0.06917144638660747,
 0.06917144638660747,
 0.0682788741998919,
 0.0682788741998919,
 0.0682788741998919,
 0.0682788741998919,
 0.0682788741998919,
 0.0682788741998919,
 0.0679889413649005,
 0.0674199862463242,
 0.06700252101728081,
 0.06700252101728081,
 0.06700252101728081,
 0.06686507980379898,
 0.06686507980379898,
 0.06632365324280728,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.06477502756312958,
 0.0646508183835236,
 0.0646508183835236,
 0.0646508183835236,
 0.0646508183835236,
 0.0646508183835236,
 0.0646508183835236,
 0.0646508183835236,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06253053994807226,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.060606060606060615,
 0.060606060606060615,
 0.060606060606060615,
 0.060606060606060615,
 0.060606060606060615,
 0.060606060606060615,
 0.05970814340265321,
 0.05970814340265321,
 0.05970814340265321,
 0.05970814340265321,
 0.05970814340265321,
 0.05970814340265321,
 0.05884898863364997,
 0.05884898863364997,
 0.05884898863364997,
 0.05884898863364997,
 0.05884898863364997,
 0.058755799361195606,
 0.05802588531856595,
 0.05802588531856595,
 0.05802588531856595,
 0.05802588531856595,
 0.05723638070321425,
 0.05723638070321425,
 0.05723638070321425,
 0.05723638070321425,
 0.05723638070321425,
 0.05723638070321425,
 0.05723638070321425,
 0.05647824947249051,
 0.05647824947249051,
 0.05647824947249051,
 0.05647824947249051,
 0.05647824947249051,
 0.05647824947249051,
 0.05647824947249051,
 0.055749467333806056,
 0.055749467333806056,
 0.055749467333806056,
 0.055749467333806056,
 0.055749467333806056,
 0.055749467333806056,
 0.055749467333806056,
 0.055749467333806056,
 0.05567022142689042,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.05437272478270369,
 0.05437272478270369,
 0.05372153093502536,
 0.05372153093502536,
 0.053093187320189895,
 0.053093187320189895,
 0.053093187320189895,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.052486388108147805,
 0.051899929610768204,
 0.051899929610768204,
 0.051899929610768204,
 0.051899929610768204,
 0.051899929610768204,
 0.051899929610768204,
 0.05133270023393454,
 0.05133270023393454,
 0.05133270023393454,
 0.05133270023393454,
 0.05133270023393454,
 0.050783671611902566,
 0.050783671611902566,
 0.050783671611902566,
 0.050783671611902566,
 0.05048616658197308,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.05025189076296061,
 0.04973647313019938,
 0.0492365963917331,
 0.0492365963917331,
 0.04875149494180871,
 0.04875149494180871,
 0.04875149494180871,
 0.0484881137876427,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.048280454958526765,
 0.047822809985881044,
 0.047822809985881044,
 0.047822809985881044,
 0.047822809985881044,
 0.04737793696791343,
 0.04737793696791343,
 0.04737793696791343,
 0.04694525268130203,
 0.04694525268130203,
 0.04694525268130203,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04652421051992355,
 0.04611429759107165,
 0.04611429759107165,
 0.04611429759107165,
 0.04611429759107165,
 0.04571503208824944,
 0.04571503208824944,
 0.04532596090993367,
 0.04532596090993367,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04494665749754947,
 0.04457671986919932,
 0.04421576882853819,
 0.04421576882853819,
 0.043863446330651264,
 0.043863446330651264,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04351941398892446,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.04222003309207491,
 0.041612518928823956,
 0.041612518928823956,
 0.041612518928823956,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04103049699311092,
 0.04074849710853642,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.039675980042907705,
 0.039675980042907705,
 0.03942082639927218,
 0.03917053290746374,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.03821501017343418,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.03798685881987932,
 0.037762745602468055,
 0.03754255278891389,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.037113480951260276,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.03629770043203139,
 0.035909478570327065,
 0.035719981318454656,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03553345272593508,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03481553119113957,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03413943709994595,
 0.03365744438798206,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.033501260508640406,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03289758474798845,
 0.03246565023717827,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.0323254091917618,
 0.03191534511615646,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03178208630818641,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.03126526997403613,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030772872744833184,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.030303030303030307,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029854071701326604,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029424494316824985,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.029012942659282975,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028618190351607124,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.028239124736245257,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027874733666903028,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027524094128159017,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.027186362391351845,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.02686076546751268,
 0.026546593660094948,
 0.026546593660094948,
 0.026546593660094948,
 0.026546593660094948,
 0.026546593660094948,
 0.026546593660094948,
 0.026546593660094948,
 0.026546593660094948,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.026243194054073903,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.025949964805384102,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.02566635011696727,
 0.025391835805951283,
 0.025391835805951283,
 0.025391835805951283,
 0.025391835805951283,
 0.025391835805951283,
 0.025391835805951283,
 0.025391835805951283,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.025125945381480306,
 0.02486823656509969,
 0.02486823656509969,
 0.02486823656509969,
 0.02486823656509969,
 0.02486823656509969,
 0.02461829819586655,
 0.02461829819586655,
 0.02461829819586655,

In [66]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [67]:
new_df[new_df['title'] == 'Avatar'].index[0]

0

In [68]:
recommend('John Carter')

Mission to Mars
The Marine 4: Moving Target
Ghosts of Mars
Get Carter
Escape from Planet Earth

In [69]:
new_df.iloc[507].title

'Independence Day'

In [70]:
import pickle

In [71]:
pickle.dump(new_df,op
            en('movies.pkl','wb'))

SyntaxError: invalid syntax (<ipython-input-71-1ee1855a6a75>, line 2)

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))